# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4af990489a9fc73eece6d9921407fbfe0509ff6693e0c3b3573437d0748f53f1b1eb5a5d2a811b8b8d2c9d40b7acb6eaa0c19103e56b206dd430ba93d9ce08bd

test:
  secret_key_base: 96f1f6c92d03d5c003923936229829c74a3849abf20a274d513ffa11fa21d27d4eda8cfb68ee2906edd1e3c77db7a5a2e605c7373d8578dab93e2f11ddcde9b1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
